Regenerated.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4503,40 +4503,31 @@ fi
 
 
 
-# If set to t, that means we are running in a shell under Emacs.
-  # If you have an Emacs named "t", then use the full path.
-  test "$EMACS" = t && EMACS=
-  for ac_prog in emacs xemacs
+for ac_prog in emacs xemacs
 do
 # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:4515: checking for $ac_word" >&5
-if eval "test \"`echo '$''{'ac_cv_path_EMACS'+set}'`\" = set"; then
+echo "configure:4512: checking for $ac_word" >&5
+if eval "test \"`echo '$''{'ac_cv_prog_EMACS'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
-  case "$EMACS" in
-  /*)
-  ac_cv_path_EMACS="$EMACS" # Let the user override the test with a path.
-  ;;
-  ?:/*)			 
-  ac_cv_path_EMACS="$EMACS" # Let the user override the test with a dos path.
-  ;;
-  *)
+  if test -n "$EMACS"; then
+  ac_cv_prog_EMACS="$EMACS" # Let the user override the test.
+else
   IFS="${IFS= 	}"; ac_save_ifs="$IFS"; IFS=":"
   ac_dummy="$PATH"
-  for ac_dir in $ac_dummy; do 
+  for ac_dir in $ac_dummy; do
     test -z "$ac_dir" && ac_dir=.
     if test -f $ac_dir/$ac_word; then
-      ac_cv_path_EMACS="$ac_dir/$ac_word"
+      ac_cv_prog_EMACS="$ac_prog"
       break
     fi
   done
   IFS="$ac_save_ifs"
-  ;;
-esac
 fi
-EMACS="$ac_cv_path_EMACS"
+fi
+EMACS="$ac_cv_prog_EMACS"
 if test -n "$EMACS"; then
   echo "$ac_t""$EMACS" 1>&6
 else
@@ -4547,32 +4538,43 @@ test -n "$EMACS" && break
 done
 test -n "$EMACS" || EMACS="no"
 
-  if test $EMACS != "no"; then
-    echo $ac_n "checking where .elc files should go""... $ac_c" 1>&6
-echo "configure:4553: checking where .elc files should go" >&5
-        lispdir="\$(datadir)/emacs/site-lisp"
-    emacs_flavor=`echo "$EMACS" | sed -e 's,^.*/,,'`
-    if test "x$prefix" = "xNONE"; then
-      if test -d $ac_default_prefix/share/$emacs_flavor/site-lisp; then
-	lispdir="\$(prefix)/share/$emacs_flavor/site-lisp"
-      else
-	if test -d $ac_default_prefix/lib/$emacs_flavor/site-lisp; then
-	  lispdir="\$(prefix)/lib/$emacs_flavor/site-lisp"
-	fi
-      fi
-    else
-      if test -d $prefix/share/$emacs_flavor/site-lisp; then
-	lispdir="\$(prefix)/share/$emacs_flavor/site-lisp"
-      else
-	if test -d $prefix/lib/$emacs_flavor/site-lisp; then
-	  lispdir="\$(prefix)/lib/$emacs_flavor/site-lisp"
-	fi
-      fi
+for ac_prog in latex latex2e
+do
+# Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
+echo "configure:4547: checking for $ac_word" >&5
+if eval "test \"`echo '$''{'ac_cv_prog_LATEX'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  if test -n "$LATEX"; then
+  ac_cv_prog_LATEX="$LATEX" # Let the user override the test.
+else
+  IFS="${IFS= 	}"; ac_save_ifs="$IFS"; IFS=":"
+  ac_dummy="$PATH"
+  for ac_dir in $ac_dummy; do
+    test -z "$ac_dir" && ac_dir=.
+    if test -f $ac_dir/$ac_word; then
+      ac_cv_prog_LATEX="$ac_prog"
+      break
     fi
-    echo "$ac_t""$lispdir" 1>&6
-  fi
-  
-EMACS=`basename $EMACS`
+  done
+  IFS="$ac_save_ifs"
+fi
+fi
+LATEX="$ac_cv_prog_LATEX"
+if test -n "$LATEX"; then
+  echo "$ac_t""$LATEX" 1>&6
+else
+  echo "$ac_t""no" 1>&6
+fi
+
+test -n "$LATEX" && break
+done
+test -n "$LATEX" || LATEX="no"
+
+test "$EMACS" != no && subdirs="lisp"
+
 
 trap '' 1 2 15
 cat > confcache <<\EOF
@@ -4679,7 +4681,6 @@ trap 'rm -fr `echo "Makefile
            config/Makefile
            demo/Makefile
            docs/Makefile
-           lisp/Makefile
            m4/Makefile
            man/Makefile
            src/Makefile
@@ -4745,7 +4746,8 @@ s%@NEXTOBJS@%$NEXTOBJS%g
 s%@TERMLIBS@%$TERMLIBS%g
 s%@TERMXLIBS@%$TERMXLIBS%g
 s%@EMACS@%$EMACS%g
-s%@lispdir@%$lispdir%g
+s%@LATEX@%$LATEX%g
+s%@subdirs@%$subdirs%g
 
 CEOF
 EOF
@@ -4791,7 +4793,6 @@ CONFIG_FILES=\${CONFIG_FILES-"Makefile
            config/Makefile
            demo/Makefile
            docs/Makefile
-           lisp/Makefile
            m4/Makefile
            man/Makefile
            src/Makefile
@@ -4978,6 +4979,103 @@ chmod +x $CONFIG_STATUS
 rm -fr confdefs* $ac_clean_files
 test "$no_create" = yes || ${CONFIG_SHELL-/bin/sh} $CONFIG_STATUS || exit 1
 
+if test "$no_recursion" != yes; then
+
+  # Remove --cache-file and --srcdir arguments so they do not pile up.
+  ac_sub_configure_args=
+  ac_prev=
+  for ac_arg in $ac_configure_args; do
+    if test -n "$ac_prev"; then
+      ac_prev=
+      continue
+    fi
+    case "$ac_arg" in
+    -cache-file | --cache-file | --cache-fil | --cache-fi \
+    | --cache-f | --cache- | --cache | --cach | --cac | --ca | --c)
+      ac_prev=cache_file ;;
+    -cache-file=* | --cache-file=* | --cache-fil=* | --cache-fi=* \
+    | --cache-f=* | --cache-=* | --cache=* | --cach=* | --cac=* | --ca=* | --c=*)
+      ;;
+    -srcdir | --srcdir | --srcdi | --srcd | --src | --sr)
+      ac_prev=srcdir ;;
+    -srcdir=* | --srcdir=* | --srcdi=* | --srcd=* | --src=* | --sr=*)
+      ;;
+    *) ac_sub_configure_args="$ac_sub_configure_args $ac_arg" ;;
+    esac
+  done
+
+  for ac_config_dir in lisp; do
+
+    # Do not complain, so a configure script can configure whichever
+    # parts of a large source tree are present.
+    if test ! -d $srcdir/$ac_config_dir; then
+      continue
+    fi
+
+    echo configuring in $ac_config_dir
+
+    case "$srcdir" in
+    .) ;;
+    *)
+      if test -d ./$ac_config_dir || mkdir ./$ac_config_dir; then :;
+      else
+        { echo "configure: error: can not create `pwd`/$ac_config_dir" 1>&2; exit 1; }
+      fi
+      ;;
+    esac
+
+    ac_popdir=`pwd`
+    cd $ac_config_dir
+
+      # A "../" for each directory in /$ac_config_dir.
+      ac_dots=`echo $ac_config_dir|sed -e 's%^\./%%' -e 's%[^/]$%&/%' -e 's%[^/]*/%../%g'`
+
+    case "$srcdir" in
+    .) # No --srcdir option.  We are building in place.
+      ac_sub_srcdir=$srcdir ;;
+    /*) # Absolute path.
+      ac_sub_srcdir=$srcdir/$ac_config_dir ;;
+    *) # Relative path.
+      ac_sub_srcdir=$ac_dots$srcdir/$ac_config_dir ;;
+    esac
+
+    # Check for guested configure; otherwise get Cygnus style configure.
+    if test -f $ac_sub_srcdir/configure; then
+      ac_sub_configure=$ac_sub_srcdir/configure
+    elif test -f $ac_sub_srcdir/configure.in; then
+      ac_sub_configure=$ac_configure
+    else
+      echo "configure: warning: no configuration information is in $ac_config_dir" 1>&2
+      ac_sub_configure=
+    fi
+
+    # The recursion is here.
+    if test -n "$ac_sub_configure"; then
+
+      # Make the cache file name correct relative to the subdirectory.
+      case "$cache_file" in
+      /*) ac_sub_cache_file=$cache_file ;;
+      *) # Relative path.
+        ac_sub_cache_file="$ac_dots$cache_file" ;;
+      esac
+  case "$ac_given_INSTALL" in
+        [/$]*) INSTALL="$ac_given_INSTALL" ;;
+        *) INSTALL="$ac_dots$ac_given_INSTALL" ;;
+        esac
+
+      echo "running ${CONFIG_SHELL-/bin/sh} $ac_sub_configure $ac_sub_configure_args --cache-file=$ac_sub_cache_file --srcdir=$ac_sub_srcdir"
+      # The eval makes quoting arguments work.
+      if eval ${CONFIG_SHELL-/bin/sh} $ac_sub_configure $ac_sub_configure_args --cache-file=$ac_sub_cache_file --srcdir=$ac_sub_srcdir
+      then :
+      else
+        { echo "configure: error: $ac_sub_configure failed for $ac_config_dir" 1>&2; exit 1; }
+      fi
+    fi
+
+    cd $ac_popdir
+  done
+fi
+
 
 eval gp_datadir=$datadir
 test $gp_datadir = NONE/share && gp_datadir=/usr/local/share
@@ -5031,6 +5129,12 @@ test "$enable_mgr" = yes && \
 
 test "$enable_rgip" = yes && \
   echo "$ac_t""  Enable RGIP terminal" 1>&6
+
+test "$EMACS" != no && \
+  echo "$ac_t""  Build lisp files" 1>&6
+
+test "$LATEX" != no && \
+  echo "$ac_t""  Build LaTeX tutorial" 1>&6
 
 test "$no_x" != yes && \
   echo "$ac_t""  Use the X Window System
